version: '3.1'
services:
  itoken-eureka:
    restart: always
    image: 10.0.2.27:5000/itoken-eureka
    container_name: itoken-eureka
    ports:
      - 8761:8761
    networks:
      - eureka_network

networks:
  eureka_network:
